spring.application.name=demo_project_auth_and_scaling

server.port=8081

spring.datasource.url=jdbc:mysql://localhost:3306/mock_eduid_db
spring.datasource.username=YOUR_DB_USERNAME
spring.datasource.password=YOUR_DB_PASSWORD
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

